spring.application.name=east2west

# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


### Email configuration ###
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
thymeleaf.templates.location=classpath:/templates/
thymeleaf.templates.extension=.html

# SerpAPI Key
serpapi.api.key=${SERP_API_KEY}


# App Properties
bezkoder.app.jwtSecret=${JWT_SECRET}
bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
#


# Enable CORS globally
#spring.webflux.cors.allow-credentials=true




spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50


# Enable SQL logging for debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

cors.allowedOrigins=${DOMAIN_URL}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/auth/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


app.verification-code.expiry-minutes=6
app.url=${URL_CLIENT}
app.oauth2.redirectUri=${GOOGLE_REDIRECT_URI}



twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.number=${TWILIO_WHATSAPP_NUMBER}

logging.level.org.springframework.security=DEBUG


SONAR_TOKEN=${SONAR_TOKEN}


amadues.api.key=${AMADEUS_API_KEY}
amadues.api.secret=${AMADEUS_API_SECRET}
amadues.api.token.url=https://test.api.amadeus.com/v1/security/oauth2/token

